workflows:
  react-native-release:
    name: React Native Release build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 20.11.1
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Android dependencies
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
